### ISSUE TITLE
Crash when loading on a dedicated server- clientside code?

### ISSUE THREAD

**Issue by ProsperCraft** [Eaglesmoddingteam/Back-to-Eco#1]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/ModelLoader

https://gist.github.com/ProsperCraft/0878c6e63ec141a5baaf62ef68f6275e

Is this trying to load clientside code when you try to run it on a server?

**Comment by ProsperCraft** [comment]
First...by the way :)

**Comment by Tebreca** [comment]
looks like the modelloader class is not found, try and reïnstall, if it still doesnt work ill try and fix it in the next version

**Comment by Tebreca** [comment]
ow im sorry, try and install a newer version of forge... your version is outdated and then the mods loading wont work

**Comment by ProsperCraft** [comment]
The forge version 2469 that was released yesterday and is the latest download from their site that I just downloaded moments ago is outdated?

**Comment by Tebreca** [comment]
you need to have forge-1.12-14.21.1.2387 at least ;-)

**Comment by Tebreca** [comment]
nope then you will meed to install a older one i guess

**Comment by ProsperCraft** [comment]
2469 is a higher number, and more recent then 2487, looks like you need updating ;)

**Comment by Tebreca** [comment]
yeah, that will be all in bte 1.0.0

**Comment by Tebreca** [comment]
i dont have time to update because ill need to rewrite the whole mod because of minecraftforge updates.

**Comment by ProsperCraft** [comment]
Here is the deal, it works fine in the client.

This is very common with new mods, I don't know exactly how it is done, but you need to have a server version in the jar that doesn't call clientside code.

Perhaps this will help- https://mcforge.readthedocs.io/en/latest/concepts/sides/

**Comment by Tebreca** [comment]
2387 is a recommended version of mcforge so try and install that one when ill figure out how to render models in the newest version.

**Comment by Tebreca** [comment]
ive got the sidedproxy problem fixed so ill create a fix release
